### ISSUE TITLE
Add readme.md?

### ISSUE THREAD

**Issue by MarcoDVisser** [gianmarcoalberti/CAinterprTools#1]
He GM, this needs a good readme. Wouldn't you agree? Otherwise people wont know what this is about!

If you don't know how feel free to steal mine:
Check my readme here --> https://github.com/MarcoDVisser/aprof/blob/master/README.md
or even better Tyler's --> https://github.com/trinker/pacman/blob/master/README.md

just add the file to your repro's root directory.

**Comment by gianmarcoalberti** [comment]
Hi Marco,
thanks for your comment. I am not so used to GitHub yet, but I tried to address your suggestion.

Cheers
Gm

**Comment by MarcoDVisser** [comment]
Sure!  Let me know if I can help.
